
server:
  port: 8082

spring:
  application:
    name: consumer-hy

  #Spring Cloud配置
  cloud:
    nacos:
      discovery:
        #是否开启注册中心，默认为true
        enabled: true
        #同“网关所在组”，因为负载均衡时会将网关所在组加上，如果不一致，负载会找不到服务实例
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        #根据自己nacos server生成的命名空间ID进行修改
        namespace: public
        username: nacos
        password: nacos
      config:
        #是否开启配置中心，默认为true
        enabled: false
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        file-extension: yaml # 配置文件格式
        #根据自己nacos server生成的命名空间ID进行修改
        namespace: public
        username: nacos
        password: nacos

dubbo:
  cloud:
    #订阅服务
    subscribed-services: producer-hy
  #扫描包
  scan:
    base-packages: com.hy
  #协议
  protocol:
    name: dubbo
    port: -1
  # 注册中心地址
  registry:
    address: nacos://localhost:8848
  provider:
    filter: HyDubboProviderTraceFilter
  consumer:
    check: false
    timeout: 600000
    filter: HyDubboConsumerTraceFilter



